+ " SELECT * FROM (select t.ticketid,t.owner,p.status, "
+ " case  "
+ " when (p.cumulativetime>'08:00:00.000' and round(tk.changedate-t.creationdate)>0 )  then  to_char(round(tk.changedate-t.creationdate)*8)||':00:00'  "
+ " when (p.cumulativetime>'08:00:00.000' and round(tk.changedate-t.creationdate)=0 )  then  '08:00:00' "
+ " when p.cumulativetime <'08:00:00.000' then p.cumulativetime "
+ " end as cumulativetime "
+ " from ticket t join PERSISTSTATUS p on p.ticketid=t.ticketid join tkstatus tk on tk.ticketid=t.ticketid "
+ " where tk.owner=t.owner and tk.status=p.status and "
+ " (t.OWNERGROUP IN ('SDNS-MNC','SDNS-SBT') or t.ASSIGNEDOWNERGROUP IN ('SDNS-MNC','SDNS-SBT')) AND t.STATUS IN ('RESOLVED','CANCELLED','CLOSED') AND t.CREATIONDATE > SYSDATE-7 "
+ " ) "
+ " PIVOT (max(cumulativetime) "
+ " for status in ('NEW','QUEUED','INPROG','PENDING','RESOLVED','CLOSED','CANCELLED')) "
